/**
 * FAQ Data Repository — Compatibility Shim
 * 
 * **THIS FILE IS A RE-EXPORT SHIM**
 * 
 * All FAQ collections have been moved to `/src/app/data/faqs/` for better organization.
 * This file maintains backward compatibility by re-exporting all collections.
 * 
 * **Architecture Change (March 5, 2026):**
 * - **Before:** 2 monolithic files (faqs.ts 725 lines + faqs-extended.ts 862 lines = 1,587 lines)
 * - **After:** 14 context-specific files + barrel index + compatibility shim
 * - **Savings:** ~400-500 lines (reduced duplication, better organization)
 * 
 * **New Structure:**
 * ```
 * /src/app/data/faqs/
 * ├── index.ts               # Barrel re-export (use this for new code)
 * ├── types.ts               # FAQ interface
 * ├── homepage.ts            # 1 collection
 * ├── services.ts            # 9 collections
 * ├── solutions.ts           # 4 collections
 * ├── about.ts               # 7 collections
 * ├── portfolio.ts           # 4 collections
 * ├── blog.ts                # 6 collections
 * ├── archives.ts            # 3 collections
 * ├── contact.ts             # 2 collections
 * ├── pricing.ts             # 3 collections
 * ├── testimonials.ts        # 2 collections
 * ├── media.ts               # 2 collections
 * ├── woocommerce.ts         # 2 collections
 * ├── technical.ts           # 6 collections
 * └── utility-pages.ts       # 4 collections
 * ```
 * 
 * **Migration Status:**
 * - Context files: 14/14 complete (100%)
 * - Barrel index: ✅ Complete
 * - Compatibility shim: ✅ Complete (this file)
 * - Template migrations: ⏳ In Progress
 * - Delete faqs-extended.ts: ⏳ Pending (after all templates migrated)
 * 
 * **Usage (Recommended):**
 * ```tsx
 * // New code should import from the barrel index:
 * import { homepageFAQs, servicesFAQs } from '@/app/data/faqs';
 * 
 * // This file maintains compatibility for existing imports:
 * import { homepageFAQs, servicesFAQs } from '../../data/faqs';
 * ```
 * 
 * **DO NOT EDIT THIS FILE**
 * Edit the context-specific files in `/src/app/data/faqs/` instead.
 * 
 * @see {@link /src/app/data/faqs/index.ts} - Barrel re-export (use for new code)
 * @see {@link /reports/2026-03/memory-reduction-p2-2-6-remaining-tasks-status.md} - Migration plan
 */

// Re-export everything from the modular faqs directory
export * from './faqs/index';
