/**
 * Extended FAQ Data Repository — Compatibility Shim
 * 
 * **THIS FILE IS A RE-EXPORT SHIM**
 * 
 * All FAQ collections have been merged into `/src/app/data/faqs/` directory.
 * This file maintains backward compatibility by re-exporting all collections.
 * 
 * **Architecture Change (March 5, 2026):**
 * - **Before:** faqs-extended.ts (862 lines) + faqs.ts (725 lines) = 1,587 lines across 2 files
 * - **After:** 14 context-specific files + barrel index in `/faqs/` directory
 * - **This file:** Compatibility shim (re-exports from new structure)
 * 
 * **Migration Path:**
 * 1. ✅ Create modular files in `/faqs/` directory (14 files)
 * 2. ✅ Create barrel index (`/faqs/index.ts`)
 * 3. ✅ Convert `faqs.ts` to compatibility shim
 * 4. ✅ Convert `faqs-extended.ts` to compatibility shim (this file)
 * 5. ⏳ Update all templates to import from `/faqs/` (33+ templates)
 * 6. ⏳ Delete compatibility shims once all imports updated
 * 
 * **Usage (Recommended):**
 * ```tsx
 * // New code should import from the barrel index:
 * import { wordpressDevelopmentFAQs, lsxDesignFAQs } from '@/app/data/faqs';
 * 
 * // This file maintains compatibility for existing imports:
 * import { wordpressDevelopmentFAQs, lsxDesignFAQs } from '../../data/faqs-extended';
 * ```
 * 
 * **DO NOT EDIT THIS FILE**
 * Edit the context-specific files in `/src/app/data/faqs/` instead.
 * 
 * **Collections Previously in This File (30):**
 * - Service FAQs: wordpressDevelopmentFAQs, woocommerceServiceFAQs, designServiceFAQs, etc. → `/faqs/services.ts`
 * - Solution FAQs: lsxDesignFAQs, wordpressSolutionFAQs, woocommerceSolutionFAQs → `/faqs/solutions.ts`
 * - Archive FAQs: blogArchiveFAQs, portfolioArchiveFAQs, etc. → `/faqs/blog.ts`, `/faqs/portfolio.ts`, `/faqs/archives.ts`
 * - Utility FAQs: error404FAQs, sitemapFAQs, etc. → `/faqs/utility-pages.ts`
 * - Company FAQs: teamPageFAQs, whyChooseUsFAQs, guaranteesFAQs → `/faqs/about.ts`
 * 
 * @see {@link /src/app/data/faqs/index.ts} - Barrel re-export (use for new code)
 * @see {@link /reports/2026-03/memory-reduction-p2-2-6-remaining-tasks-status.md} - Migration plan
 */

// Re-export everything from the modular faqs directory
export * from './faqs';

// Export the extended FAQs object for backward compatibility
import type { FAQ } from './faqs/types';

// Re-import all collections from new structure
import {
  wordpressDevelopmentFAQs,
  woocommerceServiceFAQs,
  designServiceFAQs,
  contentServiceDetailedFAQs,
  securityServiceFAQs,
  migrationsServiceDetailedFAQs,
  supportServiceFAQs,
  lsxDesignFAQs,
  wordpressSolutionFAQs,
  woocommerceSolutionFAQs,
  blogArchiveFAQs,
  portfolioArchiveFAQs,
  categoryArchiveFAQs,
  tagArchiveFAQs,
  authorArchiveFAQs,
  dateArchiveFAQs,
  searchResultsFAQs,
  singlePostFAQs,
  singlePortfolioFAQs,
  error404FAQs,
  contactPageDetailedFAQs,
  sitemapFAQs,
  pricingPageFAQs,
  testimonialsPageFAQs,
  faqPageFAQs,
  teamPageFAQs,
  whyChooseUsFAQs,
  guaranteesFAQs,
  roiCalculatorFAQs,
  tourOperatorFAQs,
} from './faqs';

/**
 * Complete FAQ collection object (backward compatibility)
 * 
 * @deprecated Import specific collections from '@/app/data/faqs' instead
 */
export const extendedFAQs = {
  // Services
  wordpressDevelopment: wordpressDevelopmentFAQs,
  woocommerceService: woocommerceServiceFAQs,
  designService: designServiceFAQs,
  contentService: contentServiceDetailedFAQs,
  securityService: securityServiceFAQs,
  migrationsService: migrationsServiceDetailedFAQs,
  supportService: supportServiceFAQs,
  
  // Solutions
  lsxDesign: lsxDesignFAQs,
  wordpressSolution: wordpressSolutionFAQs,
  woocommerceSolution: woocommerceSolutionFAQs,
  
  // Archives
  blogArchive: blogArchiveFAQs,
  portfolioArchive: portfolioArchiveFAQs,
  categoryArchive: categoryArchiveFAQs,
  tagArchive: tagArchiveFAQs,
  authorArchive: authorArchiveFAQs,
  dateArchive: dateArchiveFAQs,
  searchResults: searchResultsFAQs,
  
  // Single Pages
  singlePost: singlePostFAQs,
  singlePortfolio: singlePortfolioFAQs,
  
  // Utility Pages
  error404: error404FAQs,
  contactPage: contactPageDetailedFAQs,
  sitemap: sitemapFAQs,
  pricingPage: pricingPageFAQs,
  testimonialsPage: testimonialsPageFAQs,
  faqPage: faqPageFAQs,
  
  // About/Company
  teamPage: teamPageFAQs,
  whyChooseUs: whyChooseUsFAQs,
  guarantees: guaranteesFAQs,
  roiCalculator: roiCalculatorFAQs,
  
  // Industry-Specific
  tourOperator: tourOperatorFAQs,
};

/**
 * Helper function to get FAQs by template name (backward compatibility)
 * 
 * @deprecated Import specific collections from '@/app/data/faqs' instead
 */
export function getFAQsByTemplate(templateName: keyof typeof extendedFAQs): FAQ[] {
  return extendedFAQs[templateName] || [];
}

/**
 * Get all FAQs as flat array (backward compatibility)
 * 
 * @deprecated Import specific collections from '@/app/data/faqs' instead
 */
export function getAllExtendedFAQs(): FAQ[] {
  return Object.values(extendedFAQs).flat();
}
